GuitarScreen:
    name: 'ButtonsHome'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Chord Library'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Tab Library'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Add a Tab'

    Button:
        size_hint_y: None
        height: '48dp'
        text: 'Simon Says Challenge'
