<CBoxLayout@BoxLayout+TunerBackgroundColor>
<TunerBackgroundColor@Widget>
	pos_hint: {'center_x': .5, 'center_y': .5}
	size_hint: .9, .9
	canvas.before:
		Color:
			rgba: .2, .3, .4, 1
		Rectangle:
			size: self.size
			pos: self.pos
			
GuitarScreen:
	#Name of screen
	name: "Tuner"
	fullscreen: True
	# layout is used to pass the correct layout to the 
	# tab population function
	layout: tuner_page
	
	
	FloatLayout:
		CBoxLayout:
			id: tuner_page